name: Java CI with Maven

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Set up jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build and test with Maven
        run: mvn -B package --file pom.xml
        working-directory: .
